name: Test And lint

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Lint podfile
        run: |
          set -eo pipefail
          pod lib lint Farly.podspec
